title: AI Behaviology And CyberSoul

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'k'

enable_copy_code_button: true

mermaid:
  version: "9.1.6"

heading_anchors: true

nav_enabled: true
nav_sort: case_sensitive # Capital letters sorted before lowercase

liquid:
  error_mode: strict
  strict_filters: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "AI Behaviology and Alignment © 2024 by <a target=\"_blank\" href=\"https://github.com/AGIFOUNDATION\">AGIFoundation</a> is licensed under <a target=\"_blank\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">CC BY-NC-SA 4.0</a>"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all